CREATE DATABASE IF NOT EXISTS pro_website;
USE pro_website;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    title VARCHAR(100) NOT NULL,
    content TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);




OBERVACION AGREGAR CAMPO MARCA EN VENTAS, EN PRODUCTOS Y EN INVENTARIO


AGREGAR UN CAMPO TIPO DE PAGO EN VENTAS(CONTADO O CREDITO)

AGREGAR UNA PESTAÑA DE ABONO EN EL MODULO DE VENTAS PARA SABER SI UN CLIENTE AOBONO EN UNA COMPRA DE CREDITO





